AWSTemplateFormatVersion: 2010-09-09
Description: Spam Email Detector AWS
Parameters:
  S3Email:
    Description: 'Name of S3 bucket'
    Type: String
  Endpoint:
    Description: 'Endpoint Sagemaker'
    Type: String
Resources:
  PolicyBucket:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: '*'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref EmailSpamBucket
                - /*
      Bucket: !Ref EmailSpamBucket
  EmailSpamBucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaEmailFunction
    Properties:
      BucketName: !Ref S3Email
      AccessControl: PublicRead
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !GetAtt [LambdaEmailFunction, Arn]
    DeletionPolicy: Retain
  EmailSpamRoleLambda:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: emaillambdacloudformation-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Path: /
  LambdaEmailFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: lambda-store-nyu
        S3Key: spam-lf1.zip
      Description: lambda function for email body
      Environment:
        Variables:
          ENDPOINT_NAME: !Ref Endpoint
      FunctionName: email_lambda_cloudformation
      Handler: lambda_function.lambda_handler
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - EmailSpamRoleLambda
          - Arn
      Runtime: python3.8
      Timeout: 60
  SESRuleSet:
    Type: 'AWS::SES::ReceiptRuleSet'
  SESRule:
    Type: 'AWS::SES::ReceiptRule'
    DependsOn: EmailSpamBucket
    Properties:
      Rule:
        Actions:
          - S3Action:
              BucketName: !Ref S3Email
        Enabled: true
        ScanEnabled: false
      RuleSetName: !Ref SESRuleSet
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaEmailFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:s3:::${S3Email}'
